# Module 02 Homework - Pandas
Using a dataset from _Wine Spectator_, a wine magazine, we will practice the material that we covered in notebook M02_Colab04 to M02_Colab06.  The following questions give you more practice with filtering rows, transforming columns with `map()` and `apply()`, and data transformation with `groupby()`.

Created by Evie Ho (018929807)  
Last updated: 9/13/2026

In [1]:
import pandas as pd

csvurl="https://gist.githubusercontent.com/clairehq/" + \
        "79acab35be50eaf1c383948ed3fd1129/raw/407a02139ae1e134992b90b4b2b8c329b3d73a6a/winemag-data-130k-v2.csv"
wine = pd.read_csv(csvurl)
wine.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

**Data cleaning**  
Notice that the first column is redundant. Part of data analysis is cleaning and removing redundancy. How would you drop the redundant column inplace, that is overwrite the dataframe.

In [2]:
wine.drop(columns=['Unnamed: 0'], inplace=True)
wine.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

#### Question 1: ####  
How many countries are present in this dataset? (Only count each country once)

In [3]:
wine['country'].nunique()

41

#### Question 2: ####
How many times does each country appeared in this dataset? Show each country and the corresponding count (show counts in ascending order)

In [19]:
wine['country'].value_counts().sort_values(ascending=True)

country
Bosnia and Herzegovina        1
Slovakia                      1
Armenia                       1
Luxembourg                    4
Switzerland                   4
India                         4
Ukraine                       5
Macedonia                     6
Czech Republic                6
Cyprus                        6
Serbia                        7
Peru                          8
Morocco                      11
Lebanon                      20
Moldova                      30
Mexico                       31
Brazil                       31
England                      36
Georgia                      37
Slovenia                     39
Turkey                       43
Croatia                      44
Hungary                      61
Uruguay                      61
Romania                      67
Bulgaria                     68
Canada                      108
Greece                      242
Israel                      259
New Zealand                 733
South Africa                737
Germany                    1051
Australia                  1177
Austria                    1635
Argentina                  1907
Chile                      2258
Portugal                   2963
Spain                      3409
Italy                     10005
France                    11174
US                        27177
Name: count, dtype: int64

#### Question 3: ####
Who are the most common wine reviewers in the dataset? Create a Series whose index is the taster_twitter_handle category from the dataset, and whose values count how many reviews each person wrote.

In [5]:
wine["taster_twitter_handle"].value_counts()

taster_twitter_handle
@vossroger          13045
@wineschach          7752
@kerinokeefe         5313
@paulgwine           4851
@vboone              4696
@mattkettmann        3035
@JoeCz               2605
@wawinereport        2358
@gordone_cellars     2032
@AnneInVino          1769
@laurbuzz             938
@suskostrzewa         593
@worldwineguys        465
@bkfiona               11
@winewchristina         4
Name: count, dtype: int64

#### Question 4: ####
Create a DataFrame `italian_top` containing only the wines from Italy (`country == "Italy"`) that have `points` of at least 90.

In [6]:
italian_top = wine[(wine["country"] == "Italy") & (wine["points"] >= 90)]
italian_top.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
130,Italy,"At the first it was quite muted and subdued, b...",Bricco Rocche Brunate,91,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Brunate (Barolo),Nebbiolo,Ceretto
133,Italy,"Einaudi's wines have been improving lately, an...",NaN,91,68.0,Piedmont,Barolo,NaN,NaN,NaN,Poderi Luigi Einaudi 2003 Barolo,Nebbiolo,Poderi Luigi Einaudi
135,Italy,The color is just beginning to show signs of b...,Sorano,91,60.0,Piedmont,Barolo,NaN,NaN,NaN,Giacomo Ascheri 2001 Sorano (Barolo),Nebbiolo,Giacomo Ascheri
140,Italy,"A big, fat, luscious wine with plenty of toast...",Costa Bruna,90,26.0,Piedmont,Barbera d'Alba,NaN,NaN,NaN,Poderi Colla 2005 Costa Bruna (Barbera d'Alba),Barbera,Poderi Colla

#### Question 5: ####  
What is the mean value of the points column?

In [7]:
wine["points"].mean()

np.float64(88.43403716087269)

#### Question 6: ####
Create a variable `adjusted_price` containing the adjusted price which is the price subtracted by the average price.

*This is called **"centering" transformation** - a method commonly used in the preprocessing step before applying various machine learning algorithms.*

In [8]:
average_price = wine["price"].mean()
adjusted_price = wine["price"] - average_price
adjusted_price.head()

0          NaN
1   -20.232932
2   -21.232932
3   -22.232932
4    29.767068
Name: price, dtype: float64

#### Question 7: ####
We will consider that the "best value" wines are those that are both cheap and highly rated. Using boolean indexing (or `.query()`), find all wines with `price` under $20 and `points` of 90 or higher. How many such wines are there?
  
`query()` method in pandas enables you to filter rows in a DataFrame using a string expression instead of traditional boolean masking.

In [21]:
best_value = wine.query('price < 20 and points >= 90')
len(best_value)

1842

#### Question 8: ####
What is the name(ie., `title`) of the wine that has the highest points-to-price ratio in the dataset?
  
`points-to-price` ratio = points/price

In [10]:
ratio = wine["points"]/wine["price"]
best_wine = ratio.idxmax()
wine.loc[best_wine, "title"]

'Bandit NV Merlot (California)'

#### Question 9: ####
Use `apply()` with `axis=1` to create a function called `is_bargain_func` to run a boolean indexing that is `True` when a wine's `price` is less than 15 and its `points` is greater than 85, and `False` otherwise. Use apply() to pass your function and return output to new column `is_bargain`.

In [11]:
def is_bargain_func(row):
  if row["price"] < 15 and row["points"] > 85:
    return True
  else:
    return False
wine["is_bargain"] = wine.apply(is_bargain_func, axis=1)
wine["is_bargain"].head()

0    False
1    False
2     True
3     True
4    False
Name: is_bargain, dtype: bool

Alternative, you can use a **lamdba** function because we need to consider more than one column of the row at once. This requirement is why `.map()` alone is not sufficient.

In [12]:
wine["is_bargain"] = wine.apply(lambda row: row["price"] < 15 and row["points"] > 85, axis=1)
wine["is_bargain"].head()

0    False
1    False
2     True
3     True
4    False
Name: is_bargain, dtype: bool

#### Question 10: ####
Create a Series `flavor_counts` that contains two values: the number of wines that has the word "tart" in the `description` column and the number of wines that has the word "berries" in the `description` column. The index of the Series should be "Tart" and "Berries" for the corresponding values.

In [23]:
tart_count = wine["description"].str.contains("Tart", case=False, na=False).sum()
berries_count = wine["description"].str.contains("Berries", case=False, na=False).sum()
flavor_counts = pd.Series([tart_count, berries_count], index=["Tart", "Berries"])
flavor_counts

Tart       4424
Berries    3512
dtype: int64

#### Question 11: ####
Let's convert the points into simple star ratings.
*   A score of 90 or higher counts as 3 stars, a score of at least 80 but less than 90 is 2 stars
*   Any other score is 1 star
*   Any wines from France should automatically get 3 stars, regardless of points.

Add this new column `star_ratings` to the dataframe with the number of stars for each wine in the dataset.

In [14]:
def star_ratings(row):
  if row["country"] == "France":
    return 3
  elif row["points"] >= 90:
    return 3
  elif row["points"] >= 80:
    return 2
  else:
    return 1

wine["star_ratings"] = wine.apply(star_ratings, axis=1)
wine["star_ratings"].head()

0    2
1    2
2    2
3    2
4    2
Name: star_ratings, dtype: int64

#### Question 12: ####
What combination of countries and varieties are most common? Create a Series whose index is a MultiIndexof {country, variety} pairs. For example, a pinot noir produced in the US should map to {"US", "Pinot Noir"}. Sort the values in the Series in descending order based on wine count.

In [15]:
combination = (
    wine.groupby(["country" , "variety"])
    .size()
    .sort_values(ascending=False)
)

combination.head()

country  variety
US       Pinot Noir                  4918
         Cabernet Sauvignon          3649
         Chardonnay                  3412
France   Bordeaux-style Red Blend    2380
Italy    Red Blend                   1870
dtype: int64

#### Question 13: ####
For each `province`, compute the average `price`. Sort the results in descending order and show the top 10 provinces.

In [16]:
province_price_average = (
    wine.groupby("province")["price"]
    .mean()
    .sort_values(ascending=False)
)
province_price_average.head(10)

province
Madeira                      220.000000
Switzerland                  160.000000
Moscatel do Douro            122.666667
Puente Alto                  101.600000
Tokaji                        90.619048
Champagne                     78.389045
Rheingau                      76.913907
Santa Cruz                    75.000000
Burgundy                      70.886194
Middle and South Dalmatia     65.000000
Name: price, dtype: float64

#### Question 14: #####
Create a Series whose index is reviewers and whose values is the average score given out by that reviewer.   
*Hint*: you will need the `taster_name` and `points` columns.

In [24]:
reviewer_average_score = (
    wine.groupby("taster_name")["points"]
    .mean()
    .sort_values(ascending=True)
)
reviewer_average_score

taster_name
Alexander Peartree    86.014286
Susan Kostrzewa       86.408094
Carrie Dykes          86.644444
Michael Schachner     86.904541
Fiona Adams           87.090909
Lauren Buzzeo         87.831557
Jeff Jenssen          88.273504
Anna Lee C. Iijima    88.380506
Joe Czerwinski        88.519770
Jim Gordon            88.604331
Sean P. Sullivan      88.666243
Roger Voss            88.678957
Kerin O’Keefe         88.827969
Mike DeSimone         89.030303
Paul Gregutt          89.095032
Virginie Boone        89.229557
Christina Pickard     89.500000
Matt Kettmann         90.021087
Anne Krebiehl MW      90.587903
Name: points, dtype: float64

#### Question 15: ####
Group the dataset by reviewers (ie., `taster_name`) and use `.agg()` to compute, in a single DataFrame, the mean, min, max `points`.

In [18]:
wine.groupby("taster_name")["points"].agg(
    ["mean", "min", "max"]
)

                         mean  min  max
taster_name
Alexander Peartree  86.014286   82   91
Anna Lee C. Iijima  88.380506   81   98
Anne Krebiehl MW    90.587903   82   97
Carrie Dykes        86.644444   81   90
Christina Pickard   89.500000   87   93
Fiona Adams         87.090909   85   91
Jeff Jenssen        88.273504   82   97
Jim Gordon          88.604331   80   97
Joe Czerwinski      88.519770   80  100
Kerin O’Keefe       88.827969   80  100
Lauren Buzzeo       87.831557   81   95
Matt Kettmann       90.021087   82   97
Michael Schachner   86.904541   80   98
Mike DeSimone       89.030303   84   93
Paul Gregutt        89.095032   80   99
Roger Voss          88.678957   80  100
Sean P. Sullivan    88.666243   80   96
Susan Kostrzewa     86.408094   80   94
Virginie Boone      89.229557   80   98